export const simulatorInformation = [
  {
    totalClock: 24,
    clock: 0,
    newState: [
      { id: 1, arrival_time: 0, irruption_time: 10, size: 100 },
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 1, size: 100 },
    ],
    readySuspendState: [
      { id: 3, arrival_time: 0, irruption_time: 1, size: 100 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 2, arrival_time: 0, irruption_time: 1, size: 100 },
    finishState: [],
    memory: [
      {
        name: "Small",
        usedSpace: 0,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 100, size: 250, isInUse: true, idProcess: 2 },
    ],
    gant: [{ id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 }],
  },
  {
    totalClock: 24,
    clock: 1,
    newState: [{ id: 4, arrival_time: 1, irruption_time: 5, size: 150 }],
    readySuspendState: [
      { id: 3, arrival_time: 0, irruption_time: 1, size: 100 },
      { id: 4, arrival_time: 1, irruption_time: 5, size: 150 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
    finishState: [],
    memory: [
      {
        name: "Small",
        usedSpace: 0,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 100, size: 250, isInUse: true, idProcess: 2 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
    ],
  },
  {
    totalClock: 24,
    clock: 2,
    newState: [{ id: 5, arrival_time: 2, irruption_time: 4, size: 250 }],
    readySuspendState: [
      { id: 4, arrival_time: 1, irruption_time: 5, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
    finishState: [{ id: 2, arrival_time: 0, irruption_time: 0, size: 100 }],
    memory: [
      {
        name: "Small",
        usedSpace: 0,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 350, size: 250, isInUse: true, idProcess: 3 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
    ],
  },
  {
    totalClock: 24,
    clock: 3,
    newState: [],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 4, arrival_time: 1, irruption_time: 4, size: 150 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 0,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
    ],
  },
  {
    totalClock: 24,
    clock: 4,
    newState: [{ id: 6, arrival_time: 4, irruption_time: 1, size: 59 }],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [
      { id: 1, arrival_time: 0, irruption_time: 10, size: 100 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150 },
    ],
    runningState: { id: 6, arrival_time: 4, irruption_time: 1, size: 59 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
    ],
    memory: [
      { name: "Small", usedSpace: 59, size: 60, isInUse: true, idProcess: 6 },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
    ],
  },
  {
    totalClock: 24,
    clock: 5,
    newState: [],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150 },
      { id: 1, arrival_time: 0, irruption_time: 10, size: 100 },
    ],
    runningState: { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
    ],
    memory: [
      { name: "Small", usedSpace: 59, size: 60, isInUse: true, idProcess: 6 },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
    ],
  },
  {
    totalClock: 24,
    clock: 6,
    newState: [],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 4, arrival_time: 1, irruption_time: 3, size: 150 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
    ],
  },
  {
    totalClock: 24,
    clock: 7,
    newState: [],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 4, arrival_time: 1, irruption_time: 2, size: 150 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
    ],
  },
  {
    totalClock: 24,
    clock: 8,
    newState: [],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 4, arrival_time: 1, irruption_time: 1, size: 150 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
    ],
  },
  {
    totalClock: 24,
    clock: 9,
    newState: [],
    readySuspendState: [
      { id: 5, arrival_time: 2, irruption_time: 4, size: 250 },
    ],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 400, size: 250, isInUse: true, idProcess: 4 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
    ],
  },
  {
    totalClock: 24,
    clock: 10,
    newState: [],
    readySuspendState: [],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 5, arrival_time: 2, irruption_time: 3, size: 250 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 500, size: 250, isInUse: true, idProcess: 5 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
    ],
  },
  {
    totalClock: 24,
    clock: 11,
    newState: [],
    readySuspendState: [],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 5, arrival_time: 2, irruption_time: 2, size: 250 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 500, size: 250, isInUse: true, idProcess: 5 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
    ],
  },
  {
    totalClock: 24,
    clock: 12,
    newState: [],
    readySuspendState: [],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 5, arrival_time: 2, irruption_time: 1, size: 250 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 500, size: 250, isInUse: true, idProcess: 5 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
    ],
  },
  {
    totalClock: 24,
    clock: 13,
    newState: [],
    readySuspendState: [],
    readyState: [{ id: 1, arrival_time: 0, irruption_time: 10, size: 100 }],
    runningState: { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      { name: "Big", usedSpace: 500, size: 250, isInUse: true, idProcess: 5 },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
    ],
  },
  {
    totalClock: 24,
    clock: 14,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 9, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
    ],
  },
  {
    totalClock: 24,
    clock: 15,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 8, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
    ],
  },
  {
    totalClock: 24,
    clock: 16,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 7, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
    ],
  },
  {
    totalClock: 24,
    clock: 17,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 6, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
    ],
  },
  {
    totalClock: 24,
    clock: 18,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 5, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
      { id: 1, arrival_time: 0, irruption_time: 5, size: 100, clock: 18 },
    ],
  },
  {
    totalClock: 24,
    clock: 19,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 4, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
      { id: 1, arrival_time: 0, irruption_time: 5, size: 100, clock: 18 },
      { id: 1, arrival_time: 0, irruption_time: 4, size: 100, clock: 19 },
    ],
  },
  {
    totalClock: 24,
    clock: 20,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 3, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
      { id: 1, arrival_time: 0, irruption_time: 5, size: 100, clock: 18 },
      { id: 1, arrival_time: 0, irruption_time: 4, size: 100, clock: 19 },
      { id: 1, arrival_time: 0, irruption_time: 3, size: 100, clock: 20 },
    ],
  },
  {
    totalClock: 24,
    clock: 21,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 2, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
      { id: 1, arrival_time: 0, irruption_time: 5, size: 100, clock: 18 },
      { id: 1, arrival_time: 0, irruption_time: 4, size: 100, clock: 19 },
      { id: 1, arrival_time: 0, irruption_time: 3, size: 100, clock: 20 },
      { id: 1, arrival_time: 0, irruption_time: 2, size: 100, clock: 21 },
    ],
  },
  {
    totalClock: 24,
    clock: 22,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 1, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
      { id: 1, arrival_time: 0, irruption_time: 5, size: 100, clock: 18 },
      { id: 1, arrival_time: 0, irruption_time: 4, size: 100, clock: 19 },
      { id: 1, arrival_time: 0, irruption_time: 3, size: 100, clock: 20 },
      { id: 1, arrival_time: 0, irruption_time: 2, size: 100, clock: 21 },
      { id: 1, arrival_time: 0, irruption_time: 1, size: 100, clock: 22 },
    ],
  },
  {
    totalClock: 24,
    clock: 23,
    newState: [],
    readySuspendState: [],
    readyState: [],
    runningState: { id: 1, arrival_time: 0, irruption_time: 0, size: 100 },
    finishState: [
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250 },
    ],
    memory: [
      {
        name: "Small",
        usedSpace: 60,
        size: 60,
        isInUse: false,
        idProcess: null,
      },
      {
        name: "Medium",
        usedSpace: 100,
        size: 120,
        isInUse: true,
        idProcess: 1,
      },
      {
        name: "Big",
        usedSpace: 250,
        size: 250,
        isInUse: false,
        idProcess: null,
      },
    ],
    gant: [
      { id: 2, arrival_time: 0, irruption_time: 1, size: 100, clock: 0 },
      { id: 2, arrival_time: 0, irruption_time: 0, size: 100, clock: 1 },
      { id: 3, arrival_time: 0, irruption_time: 0, size: 100, clock: 2 },
      { id: 4, arrival_time: 1, irruption_time: 4, size: 150, clock: 3 },
      { id: 6, arrival_time: 4, irruption_time: 1, size: 59, clock: 4 },
      { id: 6, arrival_time: 4, irruption_time: 0, size: 59, clock: 5 },
      { id: 4, arrival_time: 1, irruption_time: 3, size: 150, clock: 6 },
      { id: 4, arrival_time: 1, irruption_time: 2, size: 150, clock: 7 },
      { id: 4, arrival_time: 1, irruption_time: 1, size: 150, clock: 8 },
      { id: 4, arrival_time: 1, irruption_time: 0, size: 150, clock: 9 },
      { id: 5, arrival_time: 2, irruption_time: 3, size: 250, clock: 10 },
      { id: 5, arrival_time: 2, irruption_time: 2, size: 250, clock: 11 },
      { id: 5, arrival_time: 2, irruption_time: 1, size: 250, clock: 12 },
      { id: 5, arrival_time: 2, irruption_time: 0, size: 250, clock: 13 },
      { id: 1, arrival_time: 0, irruption_time: 9, size: 100, clock: 14 },
      { id: 1, arrival_time: 0, irruption_time: 8, size: 100, clock: 15 },
      { id: 1, arrival_time: 0, irruption_time: 7, size: 100, clock: 16 },
      { id: 1, arrival_time: 0, irruption_time: 6, size: 100, clock: 17 },
      { id: 1, arrival_time: 0, irruption_time: 5, size: 100, clock: 18 },
      { id: 1, arrival_time: 0, irruption_time: 4, size: 100, clock: 19 },
      { id: 1, arrival_time: 0, irruption_time: 3, size: 100, clock: 20 },
      { id: 1, arrival_time: 0, irruption_time: 2, size: 100, clock: 21 },
      { id: 1, arrival_time: 0, irruption_time: 1, size: 100, clock: 22 },
      { id: 1, arrival_time: 0, irruption_time: 0, size: 100, clock: 23 },
    ],
  },
];
